// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOncallSchedules(t *testing.T) {
	t.Parallel()

	query := OncallSchedules()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOncallSchedulesSoftDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesQuerySoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OncallSchedules().DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesSliceSoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OncallScheduleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OncallSchedules().DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OncallScheduleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOncallSchedulesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OncallScheduleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OncallSchedule exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OncallScheduleExists to return true, but got false.")
	}
}

func testOncallSchedulesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	oncallScheduleFound, err := FindOncallSchedule(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if oncallScheduleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOncallSchedulesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OncallSchedules().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOncallSchedulesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OncallSchedules().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOncallSchedulesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	oncallScheduleOne := &OncallSchedule{}
	oncallScheduleTwo := &OncallSchedule{}
	if err = randomize.Struct(seed, oncallScheduleOne, oncallScheduleDBTypes, false, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}
	if err = randomize.Struct(seed, oncallScheduleTwo, oncallScheduleDBTypes, false, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = oncallScheduleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oncallScheduleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OncallSchedules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOncallSchedulesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	oncallScheduleOne := &OncallSchedule{}
	oncallScheduleTwo := &OncallSchedule{}
	if err = randomize.Struct(seed, oncallScheduleOne, oncallScheduleDBTypes, false, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}
	if err = randomize.Struct(seed, oncallScheduleTwo, oncallScheduleDBTypes, false, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = oncallScheduleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oncallScheduleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testOncallSchedulesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOncallSchedulesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(oncallScheduleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOncallSchedulesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOncallSchedulesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OncallScheduleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOncallSchedulesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OncallSchedules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	oncallScheduleDBTypes = map[string]string{`ID`: `uuid`, `TeamSlackID`: `text`, `Name`: `text`, `Interval`: `enum.shift_interval('daily','weekly','bi-weekly','monthly')`, `IsEnabled`: `boolean`, `StartTime`: `time with time zone`, `EndTime`: `time with time zone`, `ActiveShift`: `uuid`, `OverrideShift`: `uuid`, `SlackChannelID`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `DeletedAt`: `timestamp with time zone`}
	_                     = bytes.MinRead
)

func testOncallSchedulesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(oncallSchedulePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(oncallScheduleAllColumns) == len(oncallSchedulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallSchedulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOncallSchedulesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(oncallScheduleAllColumns) == len(oncallSchedulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OncallSchedule{}
	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallScheduleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oncallScheduleDBTypes, true, oncallSchedulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(oncallScheduleAllColumns, oncallSchedulePrimaryKeyColumns) {
		fields = oncallScheduleAllColumns
	} else {
		fields = strmangle.SetComplement(
			oncallScheduleAllColumns,
			oncallSchedulePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OncallScheduleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOncallSchedulesUpsert(t *testing.T) {
	t.Parallel()

	if len(oncallScheduleAllColumns) == len(oncallSchedulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OncallSchedule{}
	if err = randomize.Struct(seed, &o, oncallScheduleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OncallSchedule: %s", err)
	}

	count, err := OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, oncallScheduleDBTypes, false, oncallSchedulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OncallSchedule struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OncallSchedule: %s", err)
	}

	count, err = OncallSchedules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
