// Code generated by entc, DO NOT EDIT.

package privacy

import (
	"context"
	"fmt"

	"github.com/syllabix/oncall/datastore/entity"

	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with an allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with an deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns an formatted wrapped Allow decision.
func Allowf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Allow)...)
}

// Denyf returns an formatted wrapped Deny decision.
func Denyf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Deny)...)
}

// Skipf returns an formatted wrapped Skip decision.
func Skipf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Skip)...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, entity.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q entity.Query) error {
	return f(ctx, q)
}

type (
	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
)

// MutationRuleFunc type is an adapter which allows the use of
// ordinary functions as mutation rules.
type MutationRuleFunc func(context.Context, entity.Mutation) error

// EvalMutation returns f(ctx, m).
func (f MutationRuleFunc) EvalMutation(ctx context.Context, m entity.Mutation) error {
	return f(ctx, m)
}

// Policy groups query and mutation policies.
type Policy struct {
	Query    QueryPolicy
	Mutation MutationPolicy
}

// EvalQuery forwards evaluation to query a policy.
func (policy Policy) EvalQuery(ctx context.Context, q entity.Query) error {
	return policy.Query.EvalQuery(ctx, q)
}

// EvalMutation forwards evaluation to mutate a  policy.
func (policy Policy) EvalMutation(ctx context.Context, m entity.Mutation) error {
	return policy.Mutation.EvalMutation(ctx, m)
}

// QueryMutationRule is an interface which groups query and mutation rules.
type QueryMutationRule interface {
	QueryRule
	MutationRule
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return fixedDecision{Allow}
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return fixedDecision{Deny}
}

type fixedDecision struct {
	decision error
}

func (f fixedDecision) EvalQuery(context.Context, entity.Query) error {
	return f.decision
}

func (f fixedDecision) EvalMutation(context.Context, entity.Mutation) error {
	return f.decision
}

type contextDecision struct {
	eval func(context.Context) error
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return contextDecision{eval}
}

func (c contextDecision) EvalQuery(ctx context.Context, _ entity.Query) error {
	return c.eval(ctx)
}

func (c contextDecision) EvalMutation(ctx context.Context, _ entity.Mutation) error {
	return c.eval(ctx)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op entity.Op) MutationRule {
	return MutationRuleFunc(func(ctx context.Context, m entity.Mutation) error {
		if m.Op().Is(op) {
			return rule.EvalMutation(ctx, m)
		}
		return Skip
	})
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op entity.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m entity.Mutation) error {
		return Denyf("entity/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The ScheduleQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ScheduleQueryRuleFunc func(context.Context, *entity.ScheduleQuery) error

// EvalQuery return f(ctx, q).
func (f ScheduleQueryRuleFunc) EvalQuery(ctx context.Context, q entity.Query) error {
	if q, ok := q.(*entity.ScheduleQuery); ok {
		return f(ctx, q)
	}
	return Denyf("entity/privacy: unexpected query type %T, expect *entity.ScheduleQuery", q)
}

// The ScheduleMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ScheduleMutationRuleFunc func(context.Context, *entity.ScheduleMutation) error

// EvalMutation calls f(ctx, m).
func (f ScheduleMutationRuleFunc) EvalMutation(ctx context.Context, m entity.Mutation) error {
	if m, ok := m.(*entity.ScheduleMutation); ok {
		return f(ctx, m)
	}
	return Denyf("entity/privacy: unexpected mutation type %T, expect *entity.ScheduleMutation", m)
}

// The ShiftQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ShiftQueryRuleFunc func(context.Context, *entity.ShiftQuery) error

// EvalQuery return f(ctx, q).
func (f ShiftQueryRuleFunc) EvalQuery(ctx context.Context, q entity.Query) error {
	if q, ok := q.(*entity.ShiftQuery); ok {
		return f(ctx, q)
	}
	return Denyf("entity/privacy: unexpected query type %T, expect *entity.ShiftQuery", q)
}

// The ShiftMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ShiftMutationRuleFunc func(context.Context, *entity.ShiftMutation) error

// EvalMutation calls f(ctx, m).
func (f ShiftMutationRuleFunc) EvalMutation(ctx context.Context, m entity.Mutation) error {
	if m, ok := m.(*entity.ShiftMutation); ok {
		return f(ctx, m)
	}
	return Denyf("entity/privacy: unexpected mutation type %T, expect *entity.ShiftMutation", m)
}

// The UserQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserQueryRuleFunc func(context.Context, *entity.UserQuery) error

// EvalQuery return f(ctx, q).
func (f UserQueryRuleFunc) EvalQuery(ctx context.Context, q entity.Query) error {
	if q, ok := q.(*entity.UserQuery); ok {
		return f(ctx, q)
	}
	return Denyf("entity/privacy: unexpected query type %T, expect *entity.UserQuery", q)
}

// The UserMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserMutationRuleFunc func(context.Context, *entity.UserMutation) error

// EvalMutation calls f(ctx, m).
func (f UserMutationRuleFunc) EvalMutation(ctx context.Context, m entity.Mutation) error {
	if m, ok := m.(*entity.UserMutation); ok {
		return f(ctx, m)
	}
	return Denyf("entity/privacy: unexpected mutation type %T, expect *entity.UserMutation", m)
}
