// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// Shift is the predicate function for shift builders.
type Shift func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
