
-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slack_id text NOT NULL CONSTRAINT user_slack_id_uq UNIQUE,
    slack_handle text NOT NULL,
    email text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,    
    avatar_url text NOT NULL,
    display_name text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    deleted_at timestamp with time zone NULL
);

-- +migrate Down
DROP INDEX IF EXISTS user_created_at_idx;
DROP INDEX IF EXISTS user_deleted_at_idx;
DROP TABLE IF EXISTS users;
